---
name: 'Terraform PR'

on:
  pull_request:
  workflow_dispatch:

jobs:
  terraform-pr-stage:
    uses: delhage/AoC/.github/workflows/terraform_template.yaml@master
    with:
      host: https://vlinexus02.hh.atg.se
      terraform_apply: false
