---
name: 'Terraform Apply'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform-apply-stage:
    uses: delhage/AoC/.github/workflows/terraform_template.yaml@master
    secrets: inherit
    with:
      host: https://vlinexus02.hh.atg.se
      terraform_apply: true
      environment: stage
