---
name: "Test environment protection"

on:
  workflow_dispatch:

jobs:
  first-job:
    environment: prod
    steps:
      - run: echo First Job

  second-job:
    needs: first-job
    environment: prod
    steps:
      - run: echo Second Job
